### ISSUE TITLE
Possible to add object array to a Object Type?

### ISSUE THREAD

**Issue by dotChris90** [FreeOpcUa/opcua-modeler#101]
Hello team, 

just two elementary questions and maybe it is more related to the UA specification but still would like to ask here. 

 I saw that it is possible to create an Object Type (class) and add object of specific object type to this object type node. 

So image Type1 object with an object of Type2 (in OOD you would say : class1 with a property of type class2 ). 

This works but how about an array of objects? Image class1 would have a property with an array of objects of type class2. 

Question 1 ) Is this possible or arrays are strictly connected to base types like string, double, bytes, etc. ?

The next question is

Question 2 ) is it possible to have strict node types? when I defined my object type I added one object node to the root/objects folder. But I saw I was able to add properties to this node even the corresponding object type do not have this property. Is this desired and wished or is there a possibility to force object nodes following their object types strickt?    

Thank you guys a lot and enjoy your day.

**Comment by zerox1212** [comment]
These are UA questions. Maybe someone will answer but you should read more about UA or create an account at OPC Foundation so you can read the specification document yourself.

Q1: I don't remember, I never tried to do that. Maybe someone who uses arrays a lot will answer. If I were you I would get the trial version of UAExpert Modeler and just try to do it. That would be faster than asking here or reading spec.

Q2: Should be possible to enforce it (I never tried, read the spec), but I would say Object Type works more like inheritance and in most cases of OOD you want to extend a base class.
