### ISSUE TITLE
Running Latest Release in Windows

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/opcua-modeler#12]
I'm normally always running python code directly from an IDE. However today I tried to run modeler after installing via pip.

In windows you cannot do ```python opcua-modeler``` or ``` python uamodeler.py``` .

You have to open the python console and type
```
>>>from uamodeler.uamodeler import main
>>>main()
```

Am I missing something obvious?

**Comment by oroulet** [comment]
I think pip should install a script somewhere under python/scripts which is usually not in path. Standard pip stuff.

**Comment by zerox1212** [comment]
Interesting. I never knew that pip did that.

I will update the read me so it's more clear.

Thanks.
