### ISSUE TITLE
New Object From Type Should be Bold

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/opcua-modeler#16]
When adding a new object and selecting the object type, custom types should be bold.

Current:
![image](https://cloud.githubusercontent.com/assets/13090472/19196067/abdc8edc-8c79-11e6-900a-894a1cd49b90.png)

Should be like DataTypes folder:
![image](https://cloud.githubusercontent.com/assets/13090472/19196021/817a8a68-8c79-11e6-97c3-23cae1c1ad44.png)

**Comment by oroulet** [comment]
Very strange....

**Comment by oroulet** [comment]
fixed as far as I remeber. Could not reproduce now
