### ISSUE TITLE
Nodes with Children Don't Export

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/opcua-modeler#18]
Currently, adding nodes with children doesn't export all the nodes.

For example if you instantiate an Object from an Object type which has children, only the instantiated object is exported.

When an object is added, we need to search for children recursively in `_after_add` method.

**Comment by zerox1212** [comment]
I will organize some PRs to fix this.

**Comment by oroulet** [comment]
We could add an option to export _xml() to export nodes recursively...

What do you mean by instanciate? I thought I did not write code for
instantiation....

**Comment by zerox1212** [comment]
If you choose a to create a new Object, and pick a custom data type, instantiation works by default. The only problem is the new children don't get added to the export list. I think I found a simple solution which i will make a PR for soon.

**Comment by zerox1212** [comment]
https://github.com/FreeOpcUa/opcua-modeler/issues/18

With this creating a new object from a custom object type (that has multiple children) will now export the new object and all it's children correctly.

**Comment by zerox1212** [comment]
Solved with your solution of calling instantiate directly.
