### ISSUE TITLE
[0.3.1] ValueRank definition is set to "Scalar" when defining propery

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/opcua-modeler#25]
When I create a property, the attribute ValueRank is pre-set to  
![image](https://cloud.githubusercontent.com/assets/469170/20383838/9e8b760a-acb1-11e6-83f5-56ea1fb32a37.png)
This gives you some crashes when trying to change other values trying to convert "Scalar" to a int. I'd propose to set "-1" as a default

**Comment by oroulet** [comment]
fixed in opcua-widgets. Now a combox is used allowing to choose any defined value rank
