### ISSUE TITLE
[0.3.1] Random crashes with module 'opcua.ua' has no attribute 'test_bit'

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/opcua-modeler#27]
Traceback (most recent call last):
  File "\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64
\lib\site-packages\uawidgets\attrs_widget.py", line 204, in createEditor
    return BitEditor(parent, attr, dv.Value.Value)
  File "\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64
\lib\site-packages\uawidgets\attrs_widget.py", line 30, in __init__
    if ua.test_bit(val, el.value):
AttributeError: module 'opcua.ua' has no attribute 'test_bit'

**Comment by oroulet** [comment]
Thanks for the bug reports. This function has been moved...

**Comment by oroulet** [comment]
this is fixed in master already

**Comment by Stasik0** [comment]
Is there any way to pull master using pip?

**Comment by oroulet** [comment]
no. you need to clone python-opcua, then opcua-modeller then opcua-widgets
as uawidget in opcua-modeller directory. Maybe I should write a script

**Comment by Stasik0** [comment]
or just do a quick copy-paste FAQ, would be sufficient

**Comment by zerox1212** [comment]
What I normally do is pull opcua-modeler, python-opcua, opcua-widgets to my local machine. Then I copy the opcua and widgets folder into the modeler folder. After that I run it from my IDE (run app.py).

Running it in debug will let you fix lots of these little bugs from this being an early release.

**Comment by Stasik0** [comment]
@oroulet bump?

**Comment by oroulet** [comment]
What is the status here? Have you managed to run master? This is supposed to be fixed there.
If you can test master and give feedback we can make a new release. We fixed many things

**Comment by Stasik0** [comment]
Sorry, but is there some quick reference how to run master (i am familiar with git, but not python infrastructure)? It will probably be useful for other "bleeding edge"-tester as well.

**Comment by zerox1212** [comment]
Python always searches for dependencies locally first, so if you just copy the `opcua` and `uawidgets` folder to the `opcua-modeler` folder python will use that, even if you have other libraries installed with pip.

**Comment by oroulet** [comment]
you can do as @zerox1212 says or look at README file, I just updated it

**Comment by Stasik0** [comment]
@oroulet I got the following error when running app.py

  File "\freeopcua-modeler\WinPython-64bit-3.5.2.3Qt5\
python-3.5.2.amd64\lib\site-packages\uawidgets\new_node_dialogs.py", line 6, in
<module>
    from opcua.common.ua_utils import dtype_to_vtype
ImportError: cannot import name 'dtype_to_vtype'

**Comment by oroulet** [comment]
what code are you running, that method was remove a few weeks ago...
Try to run master by downloading with git as written in README

**Comment by Stasik0** [comment]
i have downloaded master, I guess it takes the wrong dependency from site-packages and ignores pythonpath

**Comment by oroulet** [comment]
probably a typo somewhere
try to write

    import uawidgets
    print(uawidhets.__file__) then you will see what module is imported

**Comment by Stasik0** [comment]
yes, typo from my side, i got master running, will test it a bit

**Comment by Stasik0** [comment]
please update readme with the line for windows
`set PYTHONPATH=%PYTHONPATH%;%cd%\python-opcua;%cd%\opcua-widgets`

**Comment by oroulet** [comment]
Great!  It should have improved quite a lot since 0.3. I am waiting for
your feedback then we can release a new version
