### ISSUE TITLE
[0.3.1] AddingReference

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/opcua-modeler#30]
Is adding references possible with the current version? Cannot find any menu or button

**Comment by oroulet** [comment]
No this is one not implemented yet. I have not had used for it yet

**Comment by Stasik0** [comment]
okay.. do we have a list of wanted features? :)

**Comment by oroulet** [comment]
Write a bug report. But this one is already written in master plan ( see
link in readme)
