### ISSUE TITLE
Add Unit Test for GUI

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/opcua-modeler#34]
If I get some free time in the next weeks I was thinking about expanding my knowledge on unit tests. I have never wrote them before.

I read this and it doesn't look that difficult, but I think we should add this to modeler.
http://johnnado.com/pyqt-qtest-example/

I will probably need help because I'm inexperienced.

**Comment by oroulet** [comment]
The approach described in this page of fundamentally broken. Events are not sent. So you cannot test your application.
I think we need to look at solutions like frologic. Can you find one that is free for open source?

**Comment by zerox1212** [comment]
Seems like there are not many options.

Some people used this: http://www.sikuli.org/

I also found this, which looks interesting, but not sure if it will work: http://pyqt.sourceforge.net/Docs/dip/automate_tutorial.html

For now I guess we could skip testing the actual GUI and just write some unit tests for the functions themselves with typical user data...

**Comment by oroulet** [comment]
Could not find anything better. I just added a test using the approach of http://johnnado.com/pyqt-qtest-example/
You can have a look. We ca do a bunch of testing that way, but we cannot test everything...

**Comment by oroulet** [comment]
need to integrate it to travis and github...

**Comment by oroulet** [comment]
Now I managed to integrate it. you can write tests!

**Comment by oroulet** [comment]
kind of works now
