### ISSUE TITLE
[0.4] How to load additional NodeSets

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/opcua-modeler#41]
I have a dedicated files for instance (i.xml) and type (t.xml) node sets. How can I load t.xml first and i.xml later and work in it? Currently I can add both of them as reference node sets, but then opening a new file reloads the whole server.

**Comment by oroulet** [comment]
Can you explain a bit more what you are trying to achieve?

**Comment by Stasik0** [comment]
Okay, I have a companion standard describing types (t.xml) and an own node set with instances of types described in (i.xml). Now, I cannot load and edit i.xml directly since the types are not there. Adding "t.xml" as a "reference node set" helps, however the existing instance in i.xml are not show since they were loaded before including t.xml

**Comment by oroulet** [comment]
OK, we have an issue here. Does your i.xml file has a reference to t.xml somewhere? We could not find it in spec, but maybe that information is under <model> tag? 

maybe as a bypass you can import i.xml after adding reference? I do not remember if the functionnality was exposed.

**Comment by Stasik0** [comment]
it has an entry as <NamespaceUris>

I can of course import i.xml after reference, but then I am editing and exporting another file (that i currently merge in i.xml manually)

**Comment by oroulet** [comment]
I really wanted to avoid having to create our own file format but it looks like we have too to solve this...

**Comment by zerox1212** [comment]
Why do you need two XML files when you can just put your types in a separate name space?

**Comment by oroulet** [comment]
added to master plan https://github.com/FreeOpcUa/opcua-modeler/issues/3 This is critical

**Comment by Stasik0** [comment]
Types are typically goverend by someone else (companion standards). I dont really want to mix classes and instances in one file.

**Comment by oroulet** [comment]
fixed in https://github.com/FreeOpcUa/opcua-modeler/pull/51
Need more testing before merge as I add to add a new file type '.uamodel'

**Comment by oroulet** [comment]
This now merged and seems to work
