### ISSUE TITLE
Wrong XML export of UAReferenceType

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/opcua-modeler#44]
Hi,

XML the export of UAReferenceType is serialized like this 
```
<DisplayName></DisplayName>
<InserseName></InverseName>
<References></References>
```

however UANodeSet.xsd requires the following order:
```
<DisplayName></DisplayName>
<References></References>
<InserseName></InverseName>
```

**Comment by oroulet** [comment]
that should fix it: https://github.com/FreeOpcUa/python-opcua/pull/438

**Comment by oroulet** [comment]
thanks for reporting
