### ISSUE TITLE
Could it cread ModellingRule?

### ISSUE THREAD

**Issue by yealfor** [FreeOpcUa/opcua-modeler#46]
I created my address space, but there is no ModellingRule in the xml. When I  implement the  new model with open62541(a opc ua sdk), it can't present the correct variant , because that variant has no ModellingRule. So help！

**Comment by zerox1212** [comment]
I also do not know how to use ModellingRule. If you can explain we can probably add it.

**Comment by yealfor** [comment]
This is a variant which can be implemented in address space:
<UAVariable BrowseName="1:State" DataType="Float" NodeId="ns=1;i=2008" ParentNodeId="ns=1;i=2005">
		<DisplayName>State</DisplayName>
		<Description>State</Description>
		<References>
			<Reference IsForward="false" ReferenceType="HasComponent">ns=1;i=2005</Reference>
			<Reference ReferenceType="HasModellingRule">i=78</Reference>
			<Reference ReferenceType="HasTypeDefinition">i=63</Reference>
		</References>
		<Value>
			<uax:Float>9.99</uax:Float>
		</Value>
	</UAVariable>
where the reference(<Reference ReferenceType="HasModellingRule">i=78</Reference>)  can't be added in free uamodeler. 
As I know, the ModellingRule includes Mandatory and Optional at least. If the ModellingRule of a variant is not Mandatory, the address space may not implement it, but there is a need to implement that variant.

**Comment by oroulet** [comment]
OK, HasModellingRule is a type reference and reference editor is not implemented yet. But this is very high on my todo list. Should have a look..

**Comment by zerox1212** [comment]
Do you have anything started with this? If you have some code already I might have time to help out with this.

**Comment by oroulet** [comment]
I have a lot of copy paste code. I need to make the basic work, then I can publish for testing/improvement

**Comment by oroulet** [comment]
started work here. https://github.com/FreeOpcUa/opcua-widgets/pull/8  
not finished. I am not sure how to modify a reference. Looks like I need to delete and rewrite it

**Comment by zerox1212** [comment]
I'll take a look at it.

**Comment by oroulet** [comment]
ready for testing now. I have not tested much myself, but it should work. suggestions to improve and PR are welcome

**Comment by oroulet** [comment]
and merged to master. So now it is easy to test
