### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by WangAllen** [FreeOpcUa/opcua-modeler#58]
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5614
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5626
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5614
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5626
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5614
qt.svg: :/folder.svg:141:6: Could not resolve property: pattern5626

and how could i connect to local opc-server?

**Comment by oroulet** [comment]
Please write bug report name that are a bit more precise ;-)
the svg stuff is warning due to extra tags in svg... we should write a svg cleaner one day.
The other question is unrelated. if you have an issue detail it
