### ISSUE TITLE
opcua modeler problem

### ISSUE THREAD

**Issue by ericccccccc** [FreeOpcUa/opcua-modeler#71]
hi~i'm start to leran about opcau open source.
i want to exec opcua-modeler, but i got this error ~

![image](https://user-images.githubusercontent.com/35401606/46461372-19481400-c7f1-11e8-9d00-2c00c76ae957.png)

**Comment by oroulet** [comment]
Your Python version is too old..

**Comment by ericccccccc** [comment]
thx for ur suggestion~ i'm also learning about python 2.
now i have update my python version to 3.6 , but i got another problems : 
 ImportError: cannot import name 'objectify'

![image](https://user-images.githubusercontent.com/35401606/46468940-83b67f80-c804-11e8-8dab-7e8a337446e8.png)


thx for your help!!

**Comment by ericccccccc** [comment]
i have fix that by install the new lxml version !
thx !!
