### ISSUE TITLE
Error defining a `Property` data type as `Guid`

### ISSUE THREAD

**Issue by the-grandson** [FreeOpcUa/opcua-modeler#75]
Can't define a `Property` data type as `Guid`, it throws the following error:

`uawidgets.utils - ERROR - badly formed hexadecimal UUID string')
Traceback (most recent call last):
  File "C:\User\python-3.6.6.amd64\lib\site-packages\uawidgets\utils.py", line 21, in wrapper
    result = func(self, *args)
  File "C:\User\python-3.6.6.amd64\lib\site-packages\uamodeler\uamodeler.py", line 324, in add_variable
    args, ok = NewUaVariableDialog.getArgs(self.modeler, "Add Variable", self._model_mgr.server_mgr, default_value=9.99)
  File "C:\User\python-3.6.6.amd64\lib\site-packages\uawidgets\new_node_dialogs.py", line 94, in getArgs
    return dialog.get_args(), True
  File "C:\User\python-3.6.6.amd64\lib\site-packages\uawidgets\new_node_dialogs.py", line 163, in get_args
    var = string_to_variant(self.valLineEdit.text(), vtype)
  File "C:\User\python-3.6.6.amd64\lib\site-packages\opcua\common\ua_utils.py", line 122, in string_to_variant
    return ua.Variant(string_to_val(string, vtype), vtype)
  File "C:\User\python-3.6.6.amd64\lib\site-packages\opcua\common\ua_utils.py", line 111, in string_to_val
    val = uuid.UUID(string)
  File "C:\User\python-3.6.6.amd64\lib\uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string`

**Comment by zerox1212** [comment]
I don't remember exactly how the window looks, does it let you enter your own UUID value?

**Comment by the-grandson** [comment]
No, the window that pop's up is the same as in the other DataTypes, check
below.
[image: GUID.PNG]

Andrew <notifications@github.com> escreveu no dia segunda, 22/10/2018 à(s)
15:30:

**Comment by zerox1212** [comment]
Your screenshot didn't work.

I have used UUID before so I know it used to work. Maybe a bug was introduced recently because not many people use UUID type.

**Comment by the-grandson** [comment]
I've modified the XML file manually and filled the property with a UUID.
Afterwards import the modified model and the modeler works just fine.
Maybe is just a problem generating a new UUID when you click 'Ok'.

Andrew <notifications@github.com> escreveu no dia terça, 23/10/2018 à(s)
16:24:

**Comment by oroulet** [comment]
the convertion is done in ua_utils.py", line 111, in string_to_val maybe you should have a look there. maybe it gets a string and want bytes or something else

**Comment by oroulet** [comment]
has anybody an example of an uuid that should works? I have noe idea since I never use them

**Comment by the-grandson** [comment]
This one `59f1dbe6-90b8-11e8-9eb6-529269fb1459` I am using, it should work.
Added manually to the XML file after exporting, and imported again with no
trouble.

oroulet <notifications@github.com> escreveu no dia sexta, 1/02/2019 à(s)
09:05:

**Comment by oroulet** [comment]
this works fine here... I do not know if that got fixed before... but I pushed a change to master so now a guuid is created automatically as defualt value. make things easier for testing, etc..

**Comment by zerox1212** [comment]
It could be that it never generated an UUID automatically?
